### ISSUE TITLE
Observer not writing at uniform times

### ISSUE THREAD

**Issue by carmaza** [sxs-collaboration/spectre#1465]
# Bug reports:

### Expected behaviour:

Evolving `Burgers` with the following options in `Step.yaml`

```                                                                                                                                                                                            
InitialTime: 0.0                                                                                         
FinalTime: 0.05                                                                                          
InitialTimeStep: 0.001

...

EventsAndTriggers:                                                                                       
  ? EveryNSlabs:                                                                                         
      N: 5                                                                                               
      Offset: 0                                                                                          
  : - Observe:                                                                                           
        VariablesToObserve: [U]                                                                          
``` 
should write observations at times 0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045 and 0.05.

### Current behavior:

In `BurgersReductions.h5`: 

```
DATA {
      (0,0): 0, 28, 0,
      (1,0): 0.001, 28, 0.189268,
      (2,0): 0.0005, 28, 0.189017,
      (3,0): 0.005, 28, 0.183449,
      (4,0): 0.006, 28, 0.182283,
      (5,0): 0.0055, 28, 0.182865,
      (6,0): 0.01, 28, 0.17782,
      (7,0): 0.011, 28, 0.176751,
      (8,0): 0.0105, 28, 0.177284,
      (9,0): 0.015, 28, 0.172682,
      (10,0): 0.016, 28, 0.171714,
      (11,0): 0.0155, 28, 0.172196,
      (12,0): 0.02, 28, 0.168054,
      (13,0): 0.021, 28, 0.167191,
      (14,0): 0.0205, 28, 0.16762,
      (15,0): 0.025, 28, 0.163956,
      (16,0): 0.026, 28, 0.1632,
      (17,0): 0.0255, 28, 0.163576,
      (18,0): 0.03, 28, 0.220669,
      (19,0): 0.031, 28, 0.219259,
      (20,0): 0.0305, 28, 0.219963,
      (21,0): 0.035, 28, 0.213739,
      (22,0): 0.036, 28, 0.212386,
      (23,0): 0.0355, 28, 0.213062,
      (24,0): 0.04, 28, 0.207097,
      (25,0): 0.041, 28, 0.205803,
      (26,0): 0.0405, 28, 0.206449,
      (27,0): 0.045, 28, 0.200752,
      (28,0): 0.046, 28, 0.19952,
      (29,0): 0.0455, 28, 0.200135
      }
```
This only occurs when the RungeKutta time stepper is being used (AdamsBashforthN works fine).
This seems to be a system-independent issue, as the same behaviour was spotted for NewtonianEuler and GeneralizedHarmonic.
