### ISSUE TITLE
InputFiles.GeneralizedHarmonic.KerrSchild.yaml.execute timeout

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1713]
The InputFiles.GeneralizedHarmonic.KerrSchild.yaml.execute test is consistently timing out when run in parallel in a debug build on my machine.  When the machine is not loaded it takes about 3 seconds, but under load it slows down, even when the load is significantly less than the number of cores.  The runtime maxes out at about 6 seconds.

I do not know the cause of the increase, but it is not specific to this test.  This one just has the largest starting value.

Can the test be sped up?  If not, can we increase the timeout?

**Comment by prayush** [comment]
Hi @wthrowe - I am not sure what the right solution here is. The current time out threshold is sufficient if the machine that the test is being run on is not loaded (I get an execution time ~3s on my laptop as well). But its not if the machine is loaded. Wouldn't this be an issue with any test that has a near-threshold execution time? Wouldn't that always become worse with increasing load on the run machine? At what load do we allow the test to begin timing out? 50%, 80%, 90%?

Possible solutions:
 * I am happy to increase the time out threshold to, say, 8 seconds from the current value of 5, but what is the right approach here?
 * I could speed up the test as well a bit, but am not sure if that would really help much. E.g. the current domain setup is:
```
DomainCreator:                                                                  
    Brick:                                                                      
      LowerBound: [4.0, -0.5, -0.5]                                             
      UpperBound: [5.0, 0.5, 0.5]                                               
      InitialRefinement: [1, 1, 1]                                              
      InitialGridPoints: [5, 5, 5]
```
I could (a) reduce the number of grid points to 4, or (b) reduce the refinement to `0`, although I don't like doing (b) as then we have no non-external boundaries.
 * The current termination time is `0.03M`, with only 2 observations being triggered in this duration. I don't think its very wise to reduce either or both of these. What do you think @geoffrey4444 ?
