### ISSUE TITLE
Parse input file headers as YAML

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#3731]
# Feature request:

Many of our test input files have headers like this:

```yaml
# Distributed under the MIT License.
# See LICENSE.txt for details.

# Executable: EvolveScalarWave3D
# Check: parse;execute_check_output
# Timeout: 10
# ExpectedOutput:
#   ScalarWaveReductions.h5
# OutputFileChecks:
#   - Label: "convergence"
#     Subfile: "/ErrorNorms.dat"
#     FileGlob: "ScalarWaveReductions.h5"
#     AbsoluteTolerance: 1e-3

DomainCreator:
  # ...
```

I propose to upgrade these headers to proper YAML syntax. YAML files can contain multiple documents separated by a `---` line, so I propose we allow input files to contain 2 documents, of which the first is discarded by the option parser if it is present:

```yaml
# Distributed under the MIT License.
# See LICENSE.txt for details.

Executable: EvolveScalarWave3D
Check: [parse, execute_check_output]
Timeout: 10
ExpectedOutput:
  - ScalarWaveReductions.h5
OutputFileChecks:
  - Label: "convergence"
    Subfile: "/ErrorNorms.dat"
    FileGlob: "ScalarWaveReductions.h5"
    AbsoluteTolerance: 1e-3

---

DomainCreator:
  # ...
```

We can then load the header as proper YAML to configure input file tests, and we can also use the header for metadata like this:

```yaml
Executable: EvolveScalarWave3D
Version: 2022.01.03
```

Input files published with papers can include such metadata to help reproducibility.
