### ISSUE TITLE
CharacteristicExtract.yaml should use ConformalFactor

### ISSUE THREAD

**Issue by keefemitman** [sxs-collaboration/spectre#4209]
# Feature request:

Change the method of initializing J in the CCE CharacteristicExtract.yaml file to ConformalFactor.

This amounts to changing
```
InitializeJ:
    InverseCubic
```
to
```
InitializeJ:
    ConformalFactor:
      AngularCoordTolerance: 1e-13
      MaxIterations: 1000
      RequireConvergence: False
      OptimizeL0Mode: True
      UseBetaIntegralEstimate: False
      ConformalFactorIterationHeuristic: SpinWeight1CoordPerturbation
      UseInputModes: False
      InputModes: []
```

Also need to update `spectre/docs/Tutorials/CCE.md` to reflect this change
