### ISSUE TITLE
"Vector sizes do not match" when observing error norms

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4245]
Trying to observe error norms on Burgers crashes the evolution with "Vector sizes do not match".  From running through a debugger, it looks like the evolved variables are on the subcell grid, but the analytic solution is on the DG grid.

Reproduce on current develop (`v2022.09.02-98-gacf1679dd`) by replacing the `EventsAndTriggers` in the test Step.yaml with
```yaml
EventsAndTriggers:
  ? Always
  : - ObserveNorms:
        SubfileName: Errors
        TensorsToObserve:
          - Name: Error(U)
            NormType: L2Norm
            Components: Sum
```
