### ISSUE TITLE
Output time steps of Cce w/ constant StepChooser doesn't match the input time step

### ISSUE THREAD

**Issue by keefemitman** [sxs-collaboration/spectre#4319]
# Bug reports:

### Expected behavior:

When the only StepChooser is Constant, the output time steps of Cce should be constant and match the input time step.

### Current behavior:

When the only StepChooser is Constant, the output time steps of Cce are *not* constant and do *not* match the input time step.

(Example of this can be found on Wheeler here: `/panfs/ds09/sxs/kmitman/spectre_cce_issues`)

@wthrowe Thanks for looking into this.

### Environment:

SpECTRE Version: 2022.09.02
Git description: 007f181
Git branch: develop
Git hash: 007f181f3308a25357fe5f2a5981e35cf8eff2fa
Hostname: wheeler
Host system: Linux-3.10.0-327.36.3.el7.x86_64
Host system version: 3.10.0-327.36.3.el7.x86_64
Host system processor: x86_64
Boost version: 1.65.1
Charm++ version: 7.0.0
CHARM_COMPILER: /usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/bin/charmc
CHARM_SHARED_LIBS: OFF
CHARM_BUILDING_BLOCKS:
CHARM_CC='mpicc '
CHARM_CXX='mpicxx '
CHARM_LD='mpicc '
CHARM_LDXX='mpicxx '
CHARM_CC_FLAGS=' -fPIC -DCMK_GFORTRAN -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_REENTRANT -I/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector '
CHARM_CXX_FLAGS=' -fPIC -DCMK_GFORTRAN -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_REENTRANT -I/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector -fno-lifetime-dse -std=gnu++11 '
CHARM_LD_FLAGS=' -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_REENTRANT -rdynamic -L/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/lib -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lpthread -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/lib/conv-static.o'
CHARM_LDXX_FLAGS=' -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_REENTRANT -rdynamic -L/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/lib -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lpthread -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/lib/conv-static.o'
CHARMBIN='/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/bin'
CHARMINC='/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/include'
CHARMLIB='/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/lib'
CHARMLIBSO=''
BLAS_LIBRARIES: /usr/local/python/anaconda3-2019.10/lib/libmkl_gf_lp64.so;/usr/local/python/anaconda3-2019.10/lib/libmkl_gnu_thread.so;/usr/local/python/anaconda3-2019.10/lib/libmkl_core.so;/usr/local/python/anaconda3-2019.10/lib/libgomp.so;-lpthread;-lm;-ldl
LAPACK_LIBRARIES: /usr/local/python/anaconda3-2019.10/lib/libmkl_gf_lp64.so;/usr/local/python/anaconda3-2019.10/lib/libmkl_gnu_thread.so;/usr/local/python/anaconda3-2019.10/lib/libmkl_core.so;/usr/local/python/anaconda3-2019.10/lib/libgomp.so;-lpthread;-lm;-ldl;-lpthread;-lm;-ldl
LIBXSMM version: 1.16.1
Blaze version: 3.8
GSL version: 1.15
HDF5 version: 1.10.4
Catch version: 2.13.3
NumPy version: 1.17.2
CMake version: 3.18.2
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -fuse-ld=lld
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /usr/local/llvm/13.0.1/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 13.0.1
CMAKE_C_COMPILER: /usr/local/llvm/13.0.1/bin/clang
CMAKE_C_COMPILER_VERSION: 13.0.1
CMAKE_Fortran_COMPILER: /usr/local/llvm/13.0.1/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 9.3.0
Python version: 3.7.4

**Comment by knelli2** [comment]
@keefemitman Can you paste the input file you were using here as well?

**Comment by keefemitman** [comment]
```yaml
ResourceInfo:
  Singletons:
    CharacteristicEvolution:
      Proc: Auto
      Exclusive: False
    H5WorldtubeBoundary:
      Proc: Auto
      Exclusive: False

Evolution:
  InitialSlabSize: 10
  InitialTimeStep: 0.1

Observers:
  VolumeFileName: "CharacteristicExtractVolume_const"
  ReductionFileName: "CharacteristicExtractUnusedReduction_const"

Cce:
  Evolution:
    TimeStepper:
      AdamsBashforthN:
        Order: 3
    StepChoosers:
      - Constant: 0.1
    StepController:
      BinaryFraction

  LMax: 20
  NumberOfRadialPoints: 12
  ObservationLMax: 8

  InitializeJ:
    ConformalFactor:
      AngularCoordTolerance: 1e-13
      MaxIterations: 1000
      RequireConvergence: False
      OptimizeL0Mode: True
      UseBetaIntegralEstimate: False
      ConformalFactorIterationHeuristic: SpinWeight1CoordPerturbation
      UseInputModes: False
      InputModes: []

  StartTime: 0
  EndTime: 10
  FixSpecNormalization: False
  BoundaryDataFilename: BondiCceR0100.h5
  ExtractionRadius: Auto
  H5Interpolator:
    BarycentricRationalSpanInterpolator:
      MinOrder: 10
      MaxOrder: 10
  H5IsBondiData: true
  H5LookaheadTimes: 200

  Filtering:
    RadialFilterHalfPower: 24
    RadialFilterAlpha: 35.0
    FilterLMax: 18

  ScriInterpOrder: 5
  ScriOutputDensity: 5
```
Edited for formatting - wthrowe
