### ISSUE TITLE
Output parse errors for std::variant

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#4868]
Currently when parsing a `std::variant` fails for any reason, it just outputs that none of the variants could be parsed. That hides any useful output from the derived types, even further down in the parsing hierarchy.

**Comment by nilsvu** [comment]
@wthrowe do you have an idea how we could fix this, or could you take a look at this?

**Comment by wthrowe** [comment]
Can you give me an example of where you are seeing this?  Collecting the errors shouldn't be too hard, but there may be a better way of doing the parse.

**Comment by nilsvu** [comment]
@ffoucart could you post one of the examples you had here?

**Comment by ffoucart** [comment]
Sure; check the options of the EvolveScalarWave3D executable but with this domain:
```
DomainCreator:
  BinaryCompactObject:
    ObjectA:
      InnerRadius: 0.5
      OuterRadius: 1.0
      XCoord: 2.0
      Interior:
        ExciseWithBoundaryCondition:
          DemandOutgoingCharSpeeds:
      UseLogarithmicMap: true
    ObjectB:
      InnerRadius: 0.5
      OuterRadius: 1.0
      XCoord: -2.0
      Interior:
        ExciseWithBoundaryCondition:
          DemandOutgoingCharSpeeds:
      UseLogarithmicMap: true
    Envelope:
      Radius: 20.0
      UseProjectiveMap: False
    OuterShell:
      Radius: 50.0
      RadialDistribution: Linear
      BoundaryCondition:
        DirichletAnalytic:
          AnalyticPrescription: *InitialData
    UseEquiangularMap: False
    InitialRefinement: [1,1,1]
    InitialGridPoints: 5

```
