### ISSUE TITLE
Checkpoint on completion

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#5094]
# Feature request:

It would be nice to have an option to the `Completion` event that also started a phase change which would checkpoint the current run. Currently we can only checkpoint based on wall clock time or slab number/time. Several times now, I've done some long runs where I have a random checkpoint in the middle because of a restart, but no checkpoint from the final time, so if I wanted to continue the run, I'd have to redo some work. I'm thinking something as simple as

```yaml
EventsAndTriggers:
  - Trigger:
      TimeCompares:
        Comparison: GreaterThanOrEqualTo
        Value: 2000.0
    Events:
      - Completion:
          WriteCheckpoint: True
```
