### ISSUE TITLE
Seemingly UB in volume output for BBH runs

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#5179]
Both @geoffrey4444 and I have encountered HDF5 errors when running some BBH simulations. But it's not consistent at all so it seems like undefined behavior. @geoffrey4444's old branch from ~May doesn't seem to have this issue so we should bisect from the April/May release to see what introduced the error.

Here are two different error messages I got.

```
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: (null) line 326 in (null)()
    major: Dataset
    minor: Unable to decrement reference count
  #4294967295: (null) line 1074 in (null)()
    major: Object atom
    minor: Unable to decrement reference count
Terminated due to an uncaught exception:

############ ERROR ############
Stack trace:

  0. /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole() [0x510f294] - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x510f294
  1. /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole() [0x510f0d6] - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x510f0d6
  2. /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole() [0x5111b55] - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x5111b55
  3. /lib64/libc.so.6(+0x35670) [0x7faf0e897670] - Resolve source file and line with: addr2line -fCpe /lib64/libc.so.6 0x35670
  4. /usr/local/HDF5/1.12.2/lib/libhdf5.so.200(+0x245cc6) [0x7faf126fbcc6] - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x245cc6
  5. H5SL_insert - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x247c41
  6. H5P_close - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x1fb371
  7. H5I_dec_ref - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x181ea8
  8. /usr/local/HDF5/1.12.2/lib/libhdf5.so.200(+0x107b77) [0x7faf125bdb77] - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x107b77
  9. H5F_try_close - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x10a65b
 10. H5O_close - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x1bf9bc
 11. H5G_close - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x14b7bb
 12. H5VL__native_group_close - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x315269
 13. H5VL_group_close - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x301d89
 14. /usr/local/HDF5/1.12.2/lib/libhdf5.so.200(+0x13f320) [0x7faf125f5320] - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x13f320
 15. H5I_dec_ref - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x181ea8
 16. H5I_dec_app_ref - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x181f67
 17. H5Gclose - Resolve source file and line with: addr2line -fCpe /usr/local/HDF5/1.12.2/lib/libhdf5.so.200 0x140cbe
 18. h5::detail::OpenGroup::~OpenGroup() - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x4a50a52
 19. h5::VolumeData::~VolumeData() - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x4a79576
 20. h5::H5File<(h5::AccessType)0>::~H5File() - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x479e5c8
 21. _ZN9observers15ThreadedActions28ContributeVolumeDataToWriter10apply_implINS_4Tags10TensorDataENS_14ObserverWriterI17EvolutionMetavarsEEN7brigand4listIJN8Parallel4Tags17MetavariablesImplIS6_EENSB_14ArrayIndexImplIiEENSB_16GlobalCacheProxyIS6_EENS3_35ExpectedContributorsForObservationsENS3_27Contribut [...] NSA_8NodeLockEEERKNS_13ObservationIdES6R_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT3_ - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x33136be

unimportant rest of backtrace...

Wall time: 04:50:37
Node: 1 Proc: 23
Line: 12 of /home/knelli/spectre/src/Utilities/ErrorHandling/SegfaultHandler.cpp
Function: void (anonymous namespace)::segfault_signal_handler(int)
Segmentation fault!
############ ERROR ############



[Partition 0][Node 0] End of program
HDF5: infinite loop closing library
      L,G_top,T_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top,G_top
```

```
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: H5A.c line 706 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: H5VLcallback.c line 1194 in H5VL_attr_read(): can't reset VOL wrapper info
    major: Virtual Object Layer
    minor: Can't reset object
  #002: H5VLint.c line 2358 in H5VL_reset_vol_wrapper(): no VOL object wrap context?
    major: Virtual Object Layer
    minor: Bad value
  #003: H5VLcallback.c line 1189 in H5VL_attr_read(): attribute read failed
    major: Virtual Object Layer
    minor: Read failed
  #004: H5VLcallback.c line 1158 in H5VL__attr_read(): attribute read failed
    major: Virtual Object Layer
    minor: Read failed
  #005: H5VLnative_attr.c line 172 in H5VL__native_attr_read(): unable to read attribute
    major: Attribute
    minor: Read failed
  #006: H5Aint.c line 646 in H5A__read(): datatype conversion failed
    major: Attribute
    minor: Unable to encode value
  #007: H5T.c line 5444 in H5T_convert(): datatype conversion failed
    major: Datatype
    minor: Can't convert datatypes
  #008: H5Tconv.c line 3344 in H5T__conv_vlen(): can't read VL data
    major: Datatype
    minor: Read failed
  #009: H5Tvlen.c line 936 in H5T__vlen_disk_read(): unable to get blob
    major: Datatype
    minor: Can't get value
  #010: H5VLcallback.c line 6923 in H5VL_blob_get(): can't reset VOL wrapper info
    major: Virtual Object Layer
    minor: Can't reset object
  #011: H5VLint.c line 2358 in H5VL_reset_vol_wrapper(): no VOL object wrap context?
    major: Virtual Object Layer
    minor: Bad value


###############################
The following exceptions were reported during the phase: Evolve
Message:
############ ERROR ############
Stack trace:

  0. /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole() [0x510f294] - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x510f294
  1. /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole() [0x510f0d6] - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x510f0d6
  2. std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > h5::read_rank1_attribute<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x47b56db
  3. h5::Header::Header(bool, h5::detail::OpenGroup&&, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x47a8a1c
  4. h5::VolumeData::VolumeData(bool, h5::detail::OpenGroup&&, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x4a56c3e
  5. h5::VolumeData& h5::H5File<(h5::AccessType)0>::try_insert<h5::VolumeData, unsigned long const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long const&) - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x30ef9e8
  6. _ZN9observers15ThreadedActions28ContributeVolumeDataToWriter10apply_implINS_4Tags10TensorDataENS_14ObserverWriterI17EvolutionMetavarsEEN7brigand4listIJN8Parallel4Tags17MetavariablesImplIS6_EENSB_14ArrayIndexImplIiEENSB_16GlobalCacheProxyIS6_EENS3_35ExpectedContributorsForObservationsENS3_27Contribut [...] NSA_8NodeLockEEERKNS_13ObservationIdES6R_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT3_ - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x33131a1
  7. _ZZN9observers7Actions20ContributeVolumeData5applyINS_8ObserverI17EvolutionMetavarsEEN7brigand4listIJN8Parallel4Tags17MetavariablesImplIS4_EENS9_14ArrayIndexImplIiEENS9_16GlobalCacheProxyIS4_EENS_4Tags35ExpectedContributorsForObservationsENSG_27ContributorsOfReductionDataENSG_24ContributorsOfTensorD [...] 6X_S7W_EEEEERKS7E_INS_14ObservationKeyES7W_S7F_IS82_ES7H_IS82_ESaIS7J_IKS82_S7W_EEEE_clES7T_S81_S8A_ - Resolve source file and line with: addr2line -fCpe /panfs/ds09/sxs/knelli/bbh_distorted_frame/head_on/Ev/new_temporal_ids_exp/EvolveGhBinaryBlackHole 0x330eb84
 

unimportant rest of backtrace...
```
